[project]
name = "basic-fastapi"
version = "0.1.0"
description = ""
authors = [
    {name = "nurulislamrimon", email = "nurulislamrimon@gmail.com"}
]
requires-python = ">=3.11"

dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.52.4,<0.53.0)",
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "psycopg (>=3.3.5,<4.0.0)",
    "alembic (>=1.19.2,<2.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "bcrypt (>=5.0.0,<6.0.0)",
    "pyjwt (>=2.13.0,<3.0.0)",
    "email-validator (>=2.3.0,<3.0.0)",
    "redis (>=8.1.0,<9.0.0)",
    "boto3 (>=1.38.0,<2.0.0)",
    "python-multipart (>=0.0.32,<0.0.33)",
]

[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"